Пишет 2 вспомогательные функции
htmlacademy-javascript/1796901-keksobooking-24 pull request #2
Opened 2021-09-27 18:52 UTC by Holder19

2021-09-28 13:08 UTC, ademaro commented on index.html
> +<>
это надо вернуть обратно

2021-09-28 13:09 UTC, ademaro commented on js/main.js
> +    getIntegerFromRange('Недопустимое значение диапазона');
getIntegerFromRange — запускаешь функцию, которую определяешь? Давай внимательнее))

2021-09-28 13:10 UTC, ademaro requested changes
Давай подправим сразу, что бы двинуть дальше, жду поправки в виде коммита и закрою ПР

2021-09-28 13:16 UTC, Holder19 commented on js/main.js
> +    getIntegerFromRange('Недопустимое значение диапазона');
ох, блин) получается я должен написать return ('Недопустимое значение диапазона') правильно понимаю?_)

2021-09-30 15:15 UTC, ademaro approved these changes
Всё круто, летим дальше) Как вариант — можно было бы в getInteregFromRange запускать getFloatFromRange с третим аргументом равным нулю)

2021-09-30 15:15 UTC, merged